//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.29 at 12:47:49 PM CEST 
//


package Models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Client complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Client">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prenom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="photo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adresse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Client", propOrder = {
        "id",
        "nom",
        "prenom",
        "photo",
        "email",
        "tel",
        "adresse"
})
public class Client
{

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String nom;
    @XmlElement(required = true)
    protected String prenom;
    @XmlElement(required = true)
    protected String photo;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String tel;
    @XmlElement(required = true)
    protected String adresse;


    /**
     * @param id      int
     * @param nom     String
     * @param prenom  String
     * @param photo   String
     * @param email   String
     * @param tel     String
     * @param adresse String
     */
    public Client(String id, String nom, String prenom, String photo, String email, String tel, String adresse)
    {
        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
        this.photo = photo;
        this.email = email;
        this.tel = tel;
        this.adresse = adresse;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId()
    {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value)
    {
        this.id = value;
    }

    /**
     * Gets the value of the nom property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNom()
    {
        return nom;
    }

    /**
     * Sets the value of the nom property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNom(String value)
    {
        this.nom = value;
    }

    /**
     * Gets the value of the prenom property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPrenom()
    {
        return prenom;
    }

    /**
     * Sets the value of the prenom property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPrenom(String value)
    {
        this.prenom = value;
    }

    /**
     * Gets the value of the photo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPhoto()
    {
        return photo;
    }

    /**
     * Sets the value of the photo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPhoto(String value)
    {
        this.photo = value;
    }

    /**
     * Gets the value of the email property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEmail()
    {
        return email;
    }

    /**
     * Sets the value of the email property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEmail(String value)
    {
        this.email = value;
    }

    /**
     * Gets the value of the tel property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTel()
    {
        return tel;
    }

    /**
     * Sets the value of the tel property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTel(String value)
    {
        this.tel = value;
    }

    /**
     * Gets the value of the adresse property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAdresse()
    {
        return adresse;
    }

    /**
     * Sets the value of the adresse property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdresse(String value)
    {
        this.adresse = value;
    }

}
